# Generated by Django 4.1.2 on 2022-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxn',
            name='Date',
            field=models.DateField(),
        ),
    ]
