# Generated by Django 4.1.2 on 2022-10-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_trxn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxn',
            name='Notes',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
